### ISSUE TITLE
MAUI Popup Docs incorrect

### ISSUE THREAD

**Issue by jayveedee** [MicrosoftDocs/CommunityToolkit#110]
The code section to show a popup is wrong. I'm not sure if this is how it's supposed to be when MAUI fully launches, but as of right now the following section is wrong and is unable to locate the `ShowPopup(popup)` function.
 `ShowPopup(popup)` needs to be replaced with `await this.ShowPopupAsync(popup)` or `this.ShowPopup(popup)` for it to work.

Example code.
```
using CommunityToolkit.Maui.Views;

public class MyPage : ContentPage
{
    public void DisplayPopup()
    {
        var popup = new SimplePopup();

        ShowPopup(popup);
    }
}
```

```
using CommunityToolkit.Maui.Views;

public class MyPage : ContentPage
{
    public void DisplayPopup()
    {
        var popup = new SimplePopup();

        await this.ShowPopupAsync(popup);
    }
}
```

**Comment by bijington** [comment]
@jayveedee thanks that is a good spot! We will add the `this.` prefix to solve that sample 👍
