### ISSUE TITLE
The XAML snippet will not work by itself. Needs c# with constructor and "InitializeComponent".

### ISSUE THREAD

**Issue by ToolmakerSteve** [MicrosoftDocs/CommunityToolkit#114]
**The XAML snippet will not work by itself.**

As seen in [my StackOverflow answer](https://stackoverflow.com/a/72510771/199364), you **also** have to have a c# code behind file, with the following contents:

	public partial class SimplePopup: CommunityToolkit.Maui.Views.Popup
	{
		public SimplePopup()
		{
			InitializeComponent();
		}
	}

Without this, you'll get error message:

> CommunityToolkit.Maui.Core.Handlers.PopupHandler found for TestApp.ProfilePopup is incompatible

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6126a74-78aa-2c4f-ce92-2cda527ca9fd
* Version Independent ID: c6126a74-78aa-2c4f-ce92-2cda527ca9fd
* Content: [Popup - .NET MAUI Community Toolkit - .NET Community Toolkit](https://docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/popup)
* Content Source: [docs/maui/views/popup.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/views/popup.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @bijington
* Microsoft Alias: **bramin**

**Comment by bijington** [comment]
Fixed by #119
