### ISSUE TITLE
CS0102	The type "WpdFileViewModel" already contains a definition for "stringsToWpdCompressorCommand

### ISSUE THREAD

**Issue by wandersonareis** [MicrosoftDocs/CommunityToolkit#125]
I am getting this error when compiling using [RelayCommand] release version 8.0 above method.

`partial class WpdFileViewModel
    {
        /// <summary>The backing field for <see cref="StringsToWpdCompressorCommand"/>.</summary>
        [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.RelayCommandGenerator", "8.0.0.0")]
        private global::CommunityToolkit.Mvvm.Input.AsyncRelayCommand? **stringsToWpdCompressorCommand**;
        /// <summary>Gets an <see cref="global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand"/> instance wrapping <see cref="StringsToWpdCompressor"/>.</summary>
        [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.RelayCommandGenerator", "8.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand StringsToWpdCompressorCommand => **stringsToWpdCompressorCommand** ??= new global::CommunityToolkit.Mvvm.Input.AsyncRelayCommand(new global::System.Func<global::System.Threading.Tasks.Task>(StringsToWpdCompressor));
    }`

**Comment by bijington** [comment]
Please open this issue on the toolkit repository over at: https://github.com/CommunityToolkit/dotnet
