### ISSUE TITLE
EventToCommandBehavior passes null EventArgs to command.

### ISSUE THREAD

**Issue by H-A-Hristov** [MicrosoftDocs/CommunityToolkit#135]
I am using version 1.2.0 CommunityToolkit.Maui
And 8.0.0 CommunityToolkit.MVVM.

`<WebView.Behaviors>
                <toolkit:EventToCommandBehavior
                    EventName="Navigated"
                    Command="{Binding NavigatedCommand}" />
            </WebView.Behaviors>`

The command is called correctly. 
`void Navigated(WebNavigatedEventArgs args)`
The arguments parameter is null.

I did not have this problem with older version of Visual Studio.
When using Microsoft.Maui.Dpendencies 6.0.400, the command parameters were not null.
Now (Dependencies 6.0.486) the problem is there.

**Comment by bijington** [comment]
@H-A-Hristov sorry to hear that you are having issues. This repository only covers the documentation, the main repository is at https://github.com/CommunityToolkit/Maui

Would you be able to open the bug there please? I will close this down for now
