### ISSUE TITLE
Replacing a registered service

### ISSUE THREAD

**Issue by Shujee** [MicrosoftDocs/CommunityToolkit#136]
There doesn't seem to be any way of replacing a registered service with a different implementation. In MVVM Light, there used to be `register` and `unregister` methods that we could use to conditionally replace a service. In Toolkit, registration seems to be a one-shot process that must be done at application startup.

Or am I missing something? All I need is a way to register a default implementation at startup and later, depending on some indeterministic criterion, switch to a different implementation.

**Comment by bijington** [comment]
I don't believe the Community Toolkits provide any DI support so I am going to close this down. Feel free to reopen it if I have misunderstood anything though.

**Comment by Shujee** [comment]
I see. It is actually `Microsoft.Extensions.DependencyInjection` and not `CommunityToolkit` which is doing registration and injection. Not sure how I got the wrong impression. Thanks for pointing out.
