### ISSUE TITLE
Please add some pictures

### ISSUE THREAD

**Issue by softlion** [MicrosoftDocs/CommunityToolkit#138]
Why no picture for a UI element ?

This should be mandatory in this doc for ALL ui elements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac138b2f-1997-c888-9439-8b97a5c5d201
* Version Independent ID: ac138b2f-1997-c888-9439-8b97a5c5d201
* Content: [Snackbar - .NET MAUI Community Toolkit - .NET Community Toolkit](https://docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/alerts/snackbar)
* Content Source: [docs/maui/alerts/snackbar.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/alerts/snackbar.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @VladislavAntonyuk
* Microsoft Alias: **bramin**

**Comment by bijington** [comment]
This has been resolved
