### ISSUE TITLE
Missing docs 

### ISSUE THREAD

**Issue by IeuanWalker** [MicrosoftDocs/CommunityToolkit#158]
Hi, did these docs a while ago but they aren't showing on the docs site for some reason - 

- https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/is-null-converter.md
- https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/is-not-null-converter.md

![image](https://user-images.githubusercontent.com/6544051/199072512-81d32465-2714-4713-b2cc-35a092bef3a2.png)

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/

**Comment by bijington** [comment]
Good spot! It looks like they got missed from the table of contents, the pages are there it's just difficult to find them

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/is-null-converter

We should aim to fix that

**Comment by bijington** [comment]
I have added PR #162 to resolve this
