### ISSUE TITLE
Community toolkit cannot be installed

### ISSUE THREAD

**Issue by sqlguy6212** [MicrosoftDocs/CommunityToolkit#175]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package CommunityToolkit.Maui 3.0.0 is not compatible with net6.0-android31.0 (.NETCoreApp,Version=v6.0) / iossimulator-x64. Package CommunityToolkit.Maui 3.0.0 supports:
  - net7.0 (.NETCoreApp,Version=v7.0)
  - net7.0-android33.0 (.NETCoreApp,Version=v7.0)
  - net7.0-ios16.0 (.NETCoreApp,Version=v7.0)
  - net7.0-maccatalyst15.4 (.NETCoreApp,Version=v7.0)
  - net7.0-tizen7.0 (.NETCoreApp,Version=v7.0)
  - net7.0-windows10.0.19041 (.NETCoreApp,Version=v7.0)	TestPopup	C:\Visual Studio Stuff\Maui\TestPopup\TestPopup\TestPopup.csproj	1	

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f2fb5332-4c1b-fc63-1be9-9032440ff424
* Version Independent ID: f2fb5332-4c1b-fc63-1be9-9032440ff424
* Content: [.NET MAUI Community Toolkit documentation - .NET Community Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/)
* Content Source: [docs/maui/index.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/index.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @bijington
* Microsoft Alias: **bramin**

**Comment by bijington** [comment]
@sqlguy6212 the latest version (3.0.0+) of the Community Toolkit for .NET MAUI requires that you are using .NET 7.0 for your application. If you want to stick with .NET 6.0 then you will need to use version 2.0.0 for now. I really wish that NuGet did a better job of handling version incompatibilities like this
