### ISSUE TITLE
Cannot add to Behaviors as it's shown

### ISSUE THREAD

**Issue by borrmann** [MicrosoftDocs/CommunityToolkit#179]
[Enter feedback here]

I assume it should be:

`this.Behaviors.Add(new StatusBarBehavior
            {
                StatusBarColor = Colors.Red,
                StatusBarStyle = StatusBarStyle.LightContent
            });`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc353757-d648-8888-d4a5-16d626c3ab76
* Version Independent ID: bc353757-d648-8888-d4a5-16d626c3ab76
* Content: [StatusBarBehavior - .NET MAUI Community Toolkit - .NET Community Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/behaviors/statusbar-behavior?tabs=ios)
* Content Source: [docs/maui/behaviors/statusbar-behavior.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/behaviors/statusbar-behavior.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @pictos
* Microsoft Alias: **bramin**

**Comment by pictos** [comment]
@borrmann I'm sorry, didn't follow you, can you give more context?

**Comment by borrmann** [comment]
Sorry, that I have been unclear. 
In the linked docs it says:

```this.Behaviors(new  StatusBarBehavior { StatusBarColor = Colors.Red, StatusBarStyle = StatusBarStyle.LightContent });```

while I believe it was meant to be:

```this.Behaviors.Add(new StatusBarBehavior { StatusBarColor = Colors.Red, StatusBarStyle = StatusBarStyle.LightContent });```

**Comment by pictos** [comment]
@borrmann, oh yeah. You're correct, do you want to submit a PR fixing it? Since it's very simple you can do it on the browser (;
