### ISSUE TITLE
A task was canceled. StateContainer

### ISSUE THREAD

**Issue by Strypper** [MicrosoftDocs/CommunityToolkit#186]
[Problem]
App crash when resize too fast or enter "Tablet" / "Desktop" first
[Platform]
Windows

    <Grid toolkit:StateContainer.CurrentState="{x:Binding CurrentDeviceState}">
        <toolkit:StateContainer.StateViews>
            <ScrollView Padding="10"
                        toolkit:StateView.StateKey="Phone">
                <Grid RowSpacing="10"
                      RowDefinitions="auto, 110, *">
                    <Frame Margin="0,50,0,0">
                        <Grid Margin="0,35,0,0"
                              RowSpacing="10"
                              RowDefinitions="auto,25,25,25,25">
                            <VerticalStackLayout>
                                <Label Text="Strypper Vandel Jason"
                                       HorizontalOptions="Center"
                                       HorizontalTextAlignment="Center"/>
                                <Switch HorizontalOptions="Center"
                                        Style="{StaticResource FollowSwithStyle}"/>
                            </VerticalStackLayout>
                            <FlexLayout Grid.Row="1"
                                        Style="{StaticResource InfoFlexLayoutStyle}">
                                <Label Text="Country"/>
                                <Label Text="Viet Nam"/>
                            </FlexLayout>
                            <FlexLayout Grid.Row="2"
                                        Style="{StaticResource InfoFlexLayoutStyle}">
                                <Label Text="Phone Number"/>
                                <Label Text="+84 0348164682"/>
                            </FlexLayout>
                            <FlexLayout Grid.Row="3"
                                        Style="{StaticResource InfoFlexLayoutStyle}">
                                <Label Text="District"/>
                                <Label Text="District 3"/>
                            </FlexLayout>
                            <FlexLayout Grid.Row="4"
                                        Style="{StaticResource InfoFlexLayoutStyle}">
                                <Label Text="Ward"/>
                                <Label Text="Vo Thi Sau"/>
                            </FlexLayout>
                        </Grid>
                    </Frame>
                    <Frame Grid.Row="1">
                        <HorizontalStackLayout HorizontalOptions="Center">
                            <toolkit:AvatarView HeightRequest="70" WidthRequest="70" CornerRadius="35"/>
                            <toolkit:AvatarView HeightRequest="70" WidthRequest="70" CornerRadius="35"/>
                            <toolkit:AvatarView HeightRequest="70" WidthRequest="70" CornerRadius="35"/>
                            <toolkit:AvatarView HeightRequest="70" WidthRequest="70" CornerRadius="35"/>
                        </HorizontalStackLayout>
                    </Frame>
                    <Frame Grid.Row="2">
                        <VerticalStackLayout>
                            <Frame Background="{x:StaticResource PremiumSubscriptionColor}">
                                <HorizontalStackLayout>
                                    <VerticalStackLayout>
                                        <Label Text="PREMIUM"/>
                                        <Label Text="Get the most for you and your pets"/>
                                    </VerticalStackLayout>
                                </HorizontalStackLayout>
                            </Frame>
                            <TableView Intent="Menu">
                                <TableRoot>
                                    <TableSection Title="Cài đặt">
                                        <ImageCell Text="Thông tin cá nhân"
                                           Detail="Cá nhân hóa thông tin cá nhân của bạn" 
                                           ImageSource="{x:StaticResource Setting24Icon}"/>
                                        <ImageCell Text="Yêu thích từ cộng đồng"
                                           Detail="1,199 bài yêu thích" 
                                           ImageSource="{x:StaticResource Heart24Icon}"/>
                                        <ImageCell Text="Theo dõi từ cộng đồng"
                                           Detail="57 tin tức đang được theo dõi" 
                                           ImageSource="{x:StaticResource New24Icon}"/>
                                        <TextCell Text="Đăng xuất" TextColor="Red"/>
                                    </TableSection>
                                </TableRoot>
                            </TableView>
                        </VerticalStackLayout>
                    </Frame>

                    <toolkit:AvatarView CornerRadius="50"
                                WidthRequest="100"
                                HeightRequest="100"
                                VerticalOptions="Start"
                                ImageSource="https://i.imgur.com/vc9FudE.jpg"/>
                </Grid>
            </ScrollView>
            <ScrollView toolkit:StateView.StateKey="Tablet">
                <Label Text="TABLET"
                       TextColor="White"
                       Style="{x:Static app:Styles.Heading1}"/>
            </ScrollView>
            <ScrollView toolkit:StateView.StateKey="Desktop">
                <Label Text="Desktop"
                       TextColor="White"
                       Style="{x:Static app:Styles.Heading1}"/>
            </ScrollView>
        </toolkit:StateContainer.StateViews>
    </Grid>

private void BasePage_SizeChanged(object sender, EventArgs e)
    {
        if(Window.Width < 500)
        {
            if(viewModel is not null)
                viewModel.CurrentDeviceState = "Phone";
        }else if(Window.Width < 900)
        {
            if (viewModel is not null)
                viewModel.CurrentDeviceState = "Tablet";
        }else if (Window.Width < 2000)
        {
            if (viewModel is not null)
                viewModel.CurrentDeviceState = "Desktop";
        }
    }
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 751a5a65-3406-7e60-660b-4c9e87bf6372
* Version Independent ID: 751a5a65-3406-7e60-660b-4c9e87bf6372
* Content: [StateContainer - .NET MAUI Community Toolkit - .NET Community Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/layouts/statecontainer)
* Content Source: [docs/maui/layouts/StateContainer.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/layouts/StateContainer.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @nicjay
* Microsoft Alias: **bramin**

**Comment by bijington** [comment]
@Strypper this repository is for the documentation on the product rather than the product itself. Could you please raised the bug over on the [.NET MAUI Community Toolkit repository](https://github.com/CommunityToolkit/Maui/issues/new/choose)
