### ISSUE TITLE
Problems with MediaElement

### ISSUE THREAD

**Issue by sqlguy6212** [MicrosoftDocs/CommunityToolkit#203]
If hot reload is not on and Volume is set to a value other than 1 such as 100 it crashes.  

Also I have a Samsung phone and after deploying to it the video plays with no volume.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d60d04b7-bb5f-24c6-4281-923117d3eb4a
* Version Independent ID: d60d04b7-bb5f-24c6-4281-923117d3eb4a
* Content: [MediaElement - .NET MAUI Community Toolkit - .NET Community Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/mediaelement)
* Content Source: [docs/maui/views/MediaElement.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/views/MediaElement.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @jfversluis
* Microsoft Alias: **joverslu**

**Comment by bijington** [comment]
This is an issue with the code rather than the documentation as as mentioned in the discussion on the code repository an issue can be raised there
