### ISSUE TITLE
Document doesn't specify what xmlns: to use to reference the Maui Community Toolkit

### ISSUE THREAD

**Issue by lrs5** [MicrosoftDocs/CommunityToolkit#218]
This document is missing a key piece of information to help the beginner use the Maui Community Toolkit.

In, say, a ContentPage, to reference, say, a MediaElement, there should be, in the <ContentPage...> element, a specification for the xmlns: value for the toolkit. This is not specified anywhere in the document.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09c65565-6de2-1fec-86c9-b64d6bb8f807
* Version Independent ID: 09c65565-6de2-1fec-86c9-b64d6bb8f807
* Content: [Getting Started with the .NET Multi-platform App UI (.NET MAUI) Community Toolkit - .NET Community Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/get-started)
* Content Source: [docs/maui/get-started.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/get-started.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @bijington
* Microsoft Alias: **joverslu**

**Comment by bijington** [comment]
The getting started pages do not include this information, they just cover how to consume the NuGet Package(s). The MediaElement specific page (https://learn.microsoft.com/dotnet/communitytoolkit/maui/views/mediaelement) does include the namespace details though. I guess we could still make this detail more explicit though.
