### ISSUE TITLE
Hyperlinks showing 404 - Page not found:

### ISSUE THREAD

**Issue by KevinDHeath** [MicrosoftDocs/CommunityToolkit#250]
The following links under "Platform APIs:" do not work and result in 404 - Page not found:
ObservableProperty, NotifyPropertyChangedFor, NotifyCanExecuteChangedFor, NotifyDataErrorInfo, NotifyPropertyChangedRecipients

This maybe due to the "Breaking Changes in 8.0.0 Preview 4"
https://github.com/CommunityToolkit/dotnet/releases/tag/v8.0.0-preview4

#288: Rename attributes, enable class-level support
[AlsoNotifyChangeFor] ---> [NotifyPropertyChangedFor]
[AlsoNotifyCanExecuteFor] ---> [NotifyCanExecuteChangedFor]
[AlsoValidateProperty] ---> [NotifyDataErrorInfo]
[AlsoBroadcastChange] ---> [NotifyPropertyChangeRecipients]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: baa399f1-fe73-add4-df84-b99a29fb4083
* Version Independent ID: baa399f1-fe73-add4-df84-b99a29fb4083
* Content: [ObservableProperty attribute - .NET Community Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/observableproperty)
* Content Source: [docs/mvvm/generators/ObservableProperty.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/mvvm/generators/ObservableProperty.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @Sergio0694
* Microsoft Alias: **joverslu**

**Comment by KevinDHeath** [comment]
Appears to have been fixed.

**Comment by YvesConan** [comment]
It's still a 404 for me:
https://learn.microsoft.com/en-us/dotnet/api/communitytoolkit.mvvm.componentmodel.NotifyPropertyChangedRecipientsAttribute

Referred from: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/observableproperty
