### ISSUE TITLE
Can't use Resources in popup

### ISSUE THREAD

**Issue by OmidTavana** [MicrosoftDocs/CommunityToolkit#253]
I'm trying to migrate my Xamarin Forms Application To .NetMaui but I'm facing an error in Popups which says u cant use Resources.
Error Code: XFC0009
Error Message : No property, BindableProperty, or event found for "Resources", or mismatching type between value and property.	
My Code : 
`<xct:Popup.Resources>
        <ResourceDictionary>
            <xct:ItemTappedEventArgsConverter x:Key="ItemTappedConverter" />
        </ResourceDictionary>
    </xct:Popup.Resources>`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6126a74-78aa-2c4f-ce92-2cda527ca9fd
* Version Independent ID: c6126a74-78aa-2c4f-ce92-2cda527ca9fd
* Content: [Popup - .NET MAUI Community Toolkit - .NET Community Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/popup)
* Content Source: [docs/maui/views/popup.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/views/popup.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @bijington
* Microsoft Alias: **joverslu**

**Comment by bijington** [comment]
I think in order to use Resources you need to place them inside a MAUI control rather than your Popup.

So this which doesn't compile:

```xaml
<toolkit:Popup>
    <toolkit:Popup.Resources>
        ...
    </toolkit:Popup.Resources>
</toolkit:Popup>
```

Can be changed to:

```xaml
<toolkit:Popup>
    <Grid>
        <Grid.Resources>
            ...
        </Grid.Resources>
    </Grid>
</toolkit:Popup>
```

**Comment by OmidTavana** [comment]
Thanks , problem solved using ur solution ✅

**Comment by bijington** [comment]
For what it's worth this is likely to change soon so that you can do as you originally wanted:

https://github.com/CommunityToolkit/Maui/pull/1351
