### ISSUE TITLE
Cannot find place to submit problems

### ISSUE THREAD

**Issue by sqlguy6212** [MicrosoftDocs/CommunityToolkit#257]
I can find no way to indicate problems I have found with the toolkit.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f2fb5332-4c1b-fc63-1be9-9032440ff424
* Version Independent ID: f2fb5332-4c1b-fc63-1be9-9032440ff424
* Content: [.NET MAUI Community Toolkit documentation - .NET Community Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/)
* Content Source: [docs/maui/index.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/index.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @bijington
* Microsoft Alias: **joverslu**

**Comment by bijington** [comment]
It is a good point that we don't explicitly state where to do this. I guess I had assumed that if you had the toolkit installed you would have used NuGet which includes a link to the project repository. That url is https://github.com/CommunityToolkit/Maui

Please do raise any issues that you have there.


We can leave this issue open and aim to add something to the documentation pages to make it more clear.
