### ISSUE TITLE
Keyboard extensions documentation errors

### ISSUE THREAD

**Issue by BioTurboNick** [MicrosoftDocs/CommunityToolkit#260]
Namespaces in examples don't match, Cancellation token argument isn't shown.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57c31da0-038c-eccc-c2f5-2a63ced6e571
* Version Independent ID: 57c31da0-038c-eccc-c2f5-2a63ced6e571
* Content: [KeyboardExtensions - .NET MAUI Community Toolkit - .NET Community Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/extensions/keyboard-extensions)
* Content Source: [docs/maui/extensions/keyboard-extensions.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/extensions/keyboard-extensions.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @PureWeen
* Microsoft Alias: **joverslu**

**Comment by bijington** [comment]
It appears that the Url to the source code doesn't work either. Did we move the KeyboardExtensions out of Core?
