### ISSUE TITLE
Popup Style not working

### ISSUE THREAD

**Issue by mike-rowley** [MicrosoftDocs/CommunityToolkit#277]
I have added the following section to Styles.xaml
    <Style TargetType="toolkit:Popup">
        <Setter Property="Color" Value="{AppThemeBinding Light={StaticResource White}, Dark={StaticResource Black}}" />
    </Style>

However my popup doesn't use these values for the Color, it comes up as an off white color: Red=0.827451, Green=0.827451, Blue=0.827451, Alpha=1

Is this a bug or am I doing something incorrect to set the consistent style for popups?

**Comment by bijington** [comment]
That is a very good question! @pictos do you have any thoughts on this?

**Comment by pictos** [comment]
I need to double check that, but from the top of my head, Popup is an `Element` and not `VisualElement`, so it doesn't have support for `Style`, but need to double check that. @PureWeen can you confirm this?

**Comment by mike-rowley** [comment]
That is correct, Popup is an Element, not a VisualElement, but IMO that seems like an oversight.  Some "Controls" adhere to Styles but some don't?  I'm sure there are technical considerations but these are the types of inconsistencies that made Xamarin such a nightmare, hopefully MAUI will have better consistencies, things like Style working 90% of the time doesn't seem like the correct solution.

**Comment by pictos** [comment]
You can try to set the style inside the Layout on the Popup... Something like:

```xml
<Popup>
    <Grid>
        <Grid.Resources>
                <Style TargetType="Label">
                        <Setter Property="FontSize" Value="20"/>
                </Style>
        </Grid.Resources>
        <Label Text="Bla" />
    </Grid>
</Popup>
```

About your thought, I would say to open a discussion on .NET MAUI repo, since this change should happen there, and it's a valid request.

**Comment by mike-rowley** [comment]
Thanks @pictos I'll open a discussion there.

**Comment by mike-rowley** [comment]
One more question I anticipate will be the response from the MAUI repo, is why is Popup based on an Element and not a VisualElement if it should have Styling capabilities?

**Comment by pictos** [comment]
If I understood your first comment, you want to be able to apply Styles on all Maui elements, right? So that is related to more stuff than a popup. 
To give you the full context around the popup.
Today popup is based as an `Element` because it can't be a `ViewHandler` the reason is to be a `ViewHandler` the control should inherit from what represents a `View` on each platform, (UIView on apple, View on Android, etc) the popup doesn't have that so it should be an `ElementHandler` and because of that an `Element` on the Maui world

**Comment by mike-rowley** [comment]
Moved to this [MAUI discussion](https://github.com/dotnet/maui/discussions/15284)
