### ISSUE TITLE
Observable Property dependent on other Observable Properties

### ISSUE THREAD

**Issue by roysurles** [MicrosoftDocs/CommunityToolkit#281]
Using Observable Property attribute, is it possible to have a Observable Property dependent on other Observable Properties?

`public partial class MyViewModel : ObservableObject
{
    [ObservableProperty]
    public bool propertyA;

    [ObservableProperty]
    public bool propertyB;

    public bool PropertyC => PropertyA && PropertyB;
}
`

![image](https://github.com/MicrosoftDocs/CommunityToolkit/assets/37274814/e48df363-432a-4069-a5e4-f4ec40d36bc9)

Where PropertyC is readonly and dependent on PropertyA and PropertyB...

Is this currently possible?  if not, is it already in the backlog or can it be submitted for new feature request?

**Comment by bijington** [comment]
Yes you can do this, you want to use the `NotifyPropertyChangedFor ` attribute.

Check out our documentation at:
https://learn.microsoft.com/en-gb/dotnet/communitytoolkit/mvvm/generators/observableproperty#notifying-dependent-properties
