### ISSUE TITLE
Add Community Toolkit to .NET Foundation projects list

### ISSUE THREAD

**Issue by AlexRadch** [MicrosoftDocs/CommunityToolkit#286]
[.NET Foundation projects list](https://dotnetfoundation.org/projects/current-projects) contains [Windows Community Toolkit](https://dotnetfoundation.org/projects/project-detail/windows-community-toolkit) but does not contains this project.
I would suggest adding the Community Toolkit to the .NET Foundation projects list as well.

**Comment by michael-hawker** [comment]
Tracked in https://github.com/dotnet-foundation/projects/issues/289, so going to close this as duplicate. Thanks! Will investigate what actually needs to be done here to get that updated.
