### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by polygonuk0036** [MicrosoftDocs/CommunityToolkit#290]
Er I hope this is the right place, thanks for all the work on the MVVM toolkit and the document below. It says 'Submit new issue' so please let me know if this is not the correct place for feedback (I clicked on the feedback button on the document).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63d6b162-0bd6-d8ce-ba45-a1d30c3162eb
* Version Independent ID: 63d6b162-0bd6-d8ce-ba45-a1d30c3162eb
* Content: [MVVM Toolkit warning MVVMTK0032 - .NET Community Toolkit](https://learn.microsoft.com/en-gb/dotnet/communitytoolkit/mvvm/generators/errors/mvvmtk0032)
* Content Source: [docs/mvvm/generators/errors/MVVMTK0032.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/mvvm/generators/errors/MVVMTK0032.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @Sergio0694
* Microsoft Alias: **joverslu**

**Comment by Sergio0694** [comment]
![ThankYouThanksGIF](https://github.com/MicrosoftDocs/CommunityToolkit/assets/10199417/be2a647e-7d8e-4165-b4ad-775e7322280b)

Thank **you**!! 😄
