### ISSUE TITLE
MediaElement to use for audio playback

### ISSUE THREAD

**Issue by kravchenko-vi** [MicrosoftDocs/CommunityToolkit#292]
Hello! I am using MediaElement to play audio and video files in a chat. 
On Windows, sound files look great:
![image](https://github.com/MicrosoftDocs/CommunityToolkit/assets/44357434/1f1fdc28-c95f-49c7-8029-89998ee8e9b9)
But on Android, they don't look very good, and it's not very intuitive how to control playback (if you don't click on the control button element, you can't see anything):
![image](https://github.com/MicrosoftDocs/CommunityToolkit/assets/44357434/5cb7eb96-0562-4fbf-97a4-5e88cbb5a2df)

I tried creating my element but it's not very stable:
![image](https://github.com/MicrosoftDocs/CommunityToolkit/assets/44357434/baeb4dc1-2008-4bcb-9fea-7397f69f072d)

Maybe you know how you can customize the display of MediaElement on Android to play audio files? I would be very grateful for your help!

**Comment by bijington** [comment]
@kravchenko-vi it might be best to ask this question over on the development repository at https://github.com/CommunityToolkit/Maui

**Comment by jfversluis** [comment]
More of a how to question than a docs issue. Closing this here.
