### ISSUE TITLE
Not Found IFileSaver in dotnet 6

### ISSUE THREAD

**Issue by bossjien26** [MicrosoftDocs/CommunityToolkit#300]
I will like IFileSaver feature to save file,

but package 2.0 not work IFileSaver in dotnet 6.

Do you know use IFileSaver in dotnet 6?

**Comment by bijington** [comment]
`FileSaver` was introduced in version v4.0.0 of the toolkit as you can see here: https://github.com/CommunityToolkit/Maui/releases/tag/4.0.0

This requires a minimum version of .NET MAUI 7.0. Why do you need version 6, can you upgrade to 7?

**Comment by bossjien26** [comment]
yeah, i do version 6 upgrade to 7, it can work, 
it's package useful, thanks you for help.
