### ISSUE TITLE
Reference to CommunityToolkit.Maui.MediaElement missing

### ISSUE THREAD

**Issue by ericbrunner** [MicrosoftDocs/CommunityToolkit#301]
Please mention that it is required to install that package` CommunityToolkit.Maui.MediaElement`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d60d04b7-bb5f-24c6-4281-923117d3eb4a
* Version Independent ID: d60d04b7-bb5f-24c6-4281-923117d3eb4a
* Content: [MediaElement - .NET MAUI Community Toolkit - .NET Community Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/mediaelement)
* Content Source: [docs/maui/views/MediaElement.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/views/MediaElement.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @jfversluis
* Microsoft Alias: **joverslu**

**Comment by bijington** [comment]
We do mention that you need to install 'the' package in the Setup section here (https://learn.microsoft.com/dotnet/communitytoolkit/maui/views/mediaelement#setup) but I guess we could clearly name it and preselect the tab for the package in the **Getting started** link
