### ISSUE TITLE
Sample app link is just GitHub repo

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/CommunityToolkit#303]
Text says to go download the sample app, but link just takes you to the repo. I’ve been unable to find the sample app download.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09c65565-6de2-1fec-86c9-b64d6bb8f807
* Version Independent ID: 09c65565-6de2-1fec-86c9-b64d6bb8f807
* Content: [Getting Started with the .NET Multi-platform App UI (.NET MAUI) Community Toolkit - .NET Community Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/get-started?tabs=CommunityToolkitMaui)
* Content Source: [docs/maui/get-started.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/get-started.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @bijington
* Microsoft Alias: **joverslu**

**Comment by bijington** [comment]
You make a good point. I can correct the statement to make it clearer that it would require downloading the source code from the repository, building and running. Or something to that effect. 

I'm assuming you were expecting to be able to download an application that you could just run?
