### ISSUE TITLE
First After Resources is wrong, second one is correct

### ISSUE THREAD

**Issue by ReySys** [MicrosoftDocs/CommunityToolkit#309]
Other resources
The [.NET MAUI Community Toolkit GitHub Repository](https://github.com/CommunityToolkit/Maui/samples) contains the source code for

Correct is this one  "https://github.com/CommunityToolkit/Maui/tree/main/samples" 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09c65565-6de2-1fec-86c9-b64d6bb8f807
* Version Independent ID: 09c65565-6de2-1fec-86c9-b64d6bb8f807
* Content: [Getting Started with the .NET Multi-platform App UI (.NET MAUI) Community Toolkit - .NET Community Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/get-started?tabs=CommunityToolkitMaui)
* Content Source: [docs/maui/get-started.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/get-started.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @bijington
* Microsoft Alias: **joverslu**

**Comment by bijington** [comment]
The link works fine for me
