### ISSUE TITLE
ListenAsync Not Awaiting Input

### ISSUE THREAD

**Issue by alaskanrogue** [MicrosoftDocs/CommunityToolkit#311]
Currently, ListenAsync is immediately returning and not waiting for something to be spoken. The code in use is very similar to the examples I have found.  Is there a time element to be set before execution of the function?

`
		internal async void GetVocalResponse()
		{
			cancellationToken = new CancellationToken();

			var RecognitionText = "";

			ISpeechToText speechToText = SpeechToText.Default;

			var recognitionResult = await speechToText.ListenAsync(
												CultureInfo.GetCultureInfo(App.activeLanguage),
												new Progress<string>(partialText =>
												{
													RecognitionText += partialText + " ";
												}), cancellationToken);

			if (recognitionResult.IsSuccessful)
			{
				RecognitionText = recognitionResult.Text;

				if (RecognitionText.Contains("yes"))
				{
					Spoke_Yes();
				}
				else
				{
					Spoke_No();
				}
			}
		}

`

**Comment by bijington** [comment]
From what I can tell `ListenAsync` should wait until something has been spoken/detected. Maybe @VladislavAntonyuk can confirm this though?

**Comment by VladislavAntonyuk** [comment]
1. Check your permissions. Probably you get an error in response
2. ListenAsync has timeout. If you don’t speak for some period of time, method return result, that Operation is Cancelled

**Comment by alaskanrogue** [comment]
During startup, microphone permission is checked and establishes a variable to control whether the `GetVocalResponse()` method is to be used or skipped. The method is called in a separate thread using `Thread(() =>`. To check the await period, I have a breakpoint set at the `if (recognitionResult.IsSuccessful)` statement. It is hit immediately.

The app is using the latest NuGet's including pre-releases, with CommunityToolkit.Maui v 5.3,  CommunityToolkit.Maui.Core v5.3 and CommunityToolkit.Maui.MediaElement v2.0.

**Comment by VladislavAntonyuk** [comment]
Most likely the issue is related to the Thread. We expect you call the method from the UI thread. Could you try call ListenAsync without Thread?

**Comment by alaskanrogue** [comment]
I wasn't calling the UI thread, but I was creating a separate thread.

**Comment by alaskanrogue** [comment]
It was in a new thread but not specifically in a UI thread. Removing the functionality from being in a separate thread worked for an Android phone but not for an iPhone.  The call is still not being awaited on the iPhone with v16.6.1.

**Comment by bijington** [comment]
Do you see any exceptions when it fails?

**Comment by bijington** [comment]
Also if the issue is reproducible it might be worth opening an issue on the repository where the code lives:

https://github.com/CommunityToolkit/Maui/issues

**Comment by VladislavAntonyuk** [comment]
on iphone make sure you granted permissions and connected to the internet

**Comment by alaskanrogue** [comment]
No exceptions. Phone is responding to remote input. These keys are present.

 `	<key>NSSpeechRecognitionUsageDescription</key>
		<string>SpeechToText requires speech recognition usage</string>
	<key>NSMicrophoneUsageDescription</key>
		<string>SpeechToText requires microphone usage</string>
`
Will try to create a reproducible project and create an issue.

**Comment by alaskanrogue** [comment]
Issue with reproduction created at: https://github.com/CommunityToolkit/Maui/issues/1415
