### ISSUE TITLE
'Toast' does not contain a definition for 'Make'

### ISSUE THREAD

**Issue by lcocea** [MicrosoftDocs/CommunityToolkit#314]
I get the exception in the title on trying to run this code:
```
CancellationTokenSource cancellationTokenSource = new CancellationTokenSource();
            await Toast
                .Make("Look busy...",
                      ToastDuration.Long,
                      14)
                .Show(cancellationTokenSource.Token);
```
Where is the documentation of the Toast.Make() method? 'Make' is not listed under the Toast methods [here](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/alerts/toast?tabs=android#methods).

**Comment by bijington** [comment]
What exception are you seeing?

It looks like we don't include the `Make` method in the methods section, this might be because it is static but I can't say for sure. The usage of it is covered in the [Syntax](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/alerts/toast?tabs=android#c) section though.

**Comment by lcocea** [comment]
> What exception are you seeing?
> 

'Toast' does not contain a definition for 'Make'

**Comment by bijington** [comment]
Ok for the record that is a compilation error and not an exception.  

Did you add this using statement as per the sample?

`using CommunityToolkit.Maui.Alerts;
`

**Comment by lcocea** [comment]
> Ok for the record that is a compilation error and not an exception.  
> 
> Did you add this using statement as per the sample?
> 
> `using CommunityToolkit.Maui.Alerts;
> `

Noted and much appreciated, thank you.
I have just realized it might be related to a limitation of the IDE I am using right now. I will investigate and close the issue if this is the case.

**Comment by bijington** [comment]
What IDE are you using?

**Comment by lcocea** [comment]
> What IDE are you using?

https://play.google.com/store/apps/details?id=com.radinc.csharpshell&hl=en&gl=US

**Comment by bijington** [comment]
Interesting! Are you building a .NET MAUI on an Android device?

**Comment by lcocea** [comment]
> Interesting! Are you building a .NET MAUI on an Android device?

Yes, I do. Actually, I learn .NetMaui on a Galaxy Tab Active3 while travelling.
