### ISSUE TITLE
Link in Android section does not work (in Badge)

### ISSUE THREAD

**Issue by DigitalNut** [MicrosoftDocs/CommunityToolkit#330]
Missing documentation (Under Badge). Link in Android section does not work. Only under Tizen section does more documentation appear. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb3c929b-661a-3203-6a38-83612d7bed15
* Version Independent ID: bb3c929b-661a-3203-6a38-83612d7bed15
* Content: [Badge - .NET MAUI Community Toolkit - Community Toolkits for .NET](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/essentials/badge?tabs=android)
* Content Source: [docs/maui/essentials/badge.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/essentials/badge.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @VladislavAntonyuk
* Microsoft Alias: **joverslu**

**Comment by bijington** [comment]
Fixed by #349
