### ISSUE TITLE
Missing code needed to enable IFolderPicker DI

### ISSUE THREAD

**Issue by thoffmann-fms** [MicrosoftDocs/CommunityToolkit#348]
To get the Toolkit working, one additional line needs to be added to the builder. Along with the reference to `IFolderPicker`, a reference to `MainPage` needs to be added:
```
            builder.Services.AddSingleton<IFolderPicker>(FolderPicker.Default);
            builder.Services.AddTransient<MainPage>();
```
Without that `MainPage` reference, the program aborts with:
```
{Microsoft.UI.Xaml.UnhandledExceptionEventArgs}
    Exception: {"Cannot dynamically create an instance of type 'xxxx.MainPage'. Reason: No parameterless constructor defined."}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85d8bed7-9442-56fa-3227-b0295e9ae651
* Version Independent ID: 85d8bed7-9442-56fa-3227-b0295e9ae651
* Content: [FolderPicker - .NET MAUI Community Toolkit - Community Toolkits for .NET](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/essentials/folder-picker?tabs=windows#examples)
* Content Source: [docs/maui/essentials/folder-picker.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/essentials/folder-picker.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @VladislavAntonyuk
* Microsoft Alias: **joverslu**

**Comment by jfversluis** [comment]
Seems like this was resolved but the issue wasn't closed. Let me do that now. Thanks for raising this with us!
