### ISSUE TITLE
Popup has a close problem

### ISSUE THREAD

**Issue by sqlguy6212** [MicrosoftDocs/CommunityToolkit#352]
I have a Popup that shows some information.  If there is no information to show (the data is retrieved in a method invoked prior to showing the Popup) I get a System.NullReferenceException: 'Object reference not set to an instance of an object.'
from both the CLose and CloseAsync.

It works in another view but I have basically duplicated the code and the error would be better if it gave some information about the object reference

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6126a74-78aa-2c4f-ce92-2cda527ca9fd
* Version Independent ID: c6126a74-78aa-2c4f-ce92-2cda527ca9fd
* Content: [Popup - .NET MAUI Community Toolkit - Community Toolkits for .NET](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/popup)
* Content Source: [docs/maui/views/popup.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/views/popup.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @bijington
* Microsoft Alias: **joverslu**

**Comment by bijington** [comment]
@sqlguy6212 what information do you see in the StackTrace from the exception?

**Comment by jfversluis** [comment]
No response so going to assume this is resolved.
