### ISSUE TITLE
[Enhancement] Automatically set the popup size to wrap around its content

### ISSUE THREAD

**Issue by BeepBeepBopBop** [MicrosoftDocs/CommunityToolkit#356]
Same proposition as here: https://github.com/xamarin/XamarinCommunityToolkit/issues/937

Basically just providing some option with Popups to allow for their size to be automatically determined by their child content.

**Comment by bijington** [comment]
@BeepBeepBopBop this should now be possible in the .NET MAUI Community Toolkit

**Comment by BeepBeepBopBop** [comment]
My bad, I did not find that information. Would you mind sharing a bit more about it ? Thanks a lot for your help.
