### ISSUE TITLE
Labels without end tags

### ISSUE THREAD

**Issue by kenllyacosta** [MicrosoftDocs/CommunityToolkit#357]
At the page: "https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/semantic-order-view" there are 2 labels which does not end with />

Example:

```
<Label x:Name="DescriptionLabel" Text="{Binding Description}">
<Label x:Name="TitleLabel" Text="{Binding Title}" FontSize="30">
```

They should end with />

Example:

```
<Label x:Name="DescriptionLabel" Text="{Binding Description}"/>
<Label x:Name="TitleLabel" Text="{Binding Title}" FontSize="30"/>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8729d02-fdc7-9c5d-6160-b385946961bc
* Version Independent ID: f8729d02-fdc7-9c5d-6160-b385946961bc
* Content: [SemanticOrderView - .NET MAUI Community Toolkit - Community Toolkits for .NET](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/semantic-order-view)
* Content Source: [docs/maui/views/semantic-order-view.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/views/semantic-order-view.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @bijington
* Microsoft Alias: **joverslu**

**Comment by jfversluis** [comment]
You're totally right, thank you!
