### ISSUE TITLE
Missing line of code to enable sample to work

### ISSUE THREAD

**Issue by sej69** [MicrosoftDocs/CommunityToolkit#363]
### Type of issue

Code doesn't work

### Description

[Enter feedback here]
Under dependency Registation, the MainPage is not registered and the user will get the error message
"System.MissingMethodException: 'No parameterless constructor defined for type 'appname.MainPage'.'"

The correct dependency registration will look like this:

`        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .UseMauiCommunityToolkit()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                    fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
                });
            builder.Services.AddSingleton<ISpeechToText>(SpeechToText.Default);
            builder.Services.AddTransient<MainPage>();

#if DEBUG
            builder.Logging.AddDebug();
#endif

            return builder.Build();
        }
    }`

Note the additional line:             builder.Services.AddTransient<MainPage>();

### Page URL

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/essentials/speech-to-text?tabs=ios

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/essentials/speech-to-text.md

### Document Version Independent Id

bd555d8e-ea79-876f-5108-fd6bb19d0d8a

### Article author

@VladislavAntonyuk

### Metadata

* ID: bd555d8e-ea79-876f-5108-fd6bb19d0d8a 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by jfversluis** [comment]
No response for a long time so assuming this issue has been resolved, thank you!
