### ISSUE TITLE
Required Android Permission Requirements Unclear

### ISSUE THREAD

**Issue by jlinstrum** [MicrosoftDocs/CommunityToolkit#368]
### Type of issue

Typo

### Description

The document says: 

```
The following preconditions are required for the FileSaver:

If your target device API level is less than 33 add permissions to AndroidManifest.xml:
  ...
When your app targets Android API level 34 and up, no additional permissions are required.
```
These statements make it unclear if API level 33 requires permissions be added to the Manifest or not. This is kind of important information since API level 33 is about as high as one might want to go right now if you want your app to be available to at least half of the market.

By the way, I believe that API level 33 is probably supported since that is when Android added a media picker to their OS (I haven't verified by checking the code).  So, the second line should probably read:

`When your app targets Android API level 33 and up, no additional permissions are required.`

### Page URL

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/essentials/file-saver?tabs=android

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/essentials/file-saver.md

### Document Version Independent Id

19b55d62-25cf-3589-9ac5-450b1555f18a

### Article author

@VladislavAntonyuk

### Metadata

* ID: 19b55d62-25cf-3589-9ac5-450b1555f18a 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by jfversluis** [comment]
Since this we have added additional information about the API levels, therefore assuming this has been resolved. If that is not the case, please let us know, thank you!
