### ISSUE TITLE
Keyboard overlaps content when WindowManagerFlags.LayoutNoLimits is added to window flags

### ISSUE THREAD

**Issue by irving-guerrero** [MicrosoftDocs/CommunityToolkit#373]
### Type of issue

Code doesn't work

### Description

When Window.AddFlags(WindowManagerFlags.LayoutNoLimits); is set end KeyboardExtensions.ShowKeyboardAsync is executed, keyboard overlaps content
![MicrosoftTeams-image (57)](https://github.com/MicrosoftDocs/CommunityToolkit/assets/63170841/db19c596-16e1-404b-b448-5185f62bcb3b)
![MicrosoftTeams-image (58)](https://github.com/MicrosoftDocs/CommunityToolkit/assets/63170841/735e88af-d2c6-4acb-9d42-bb2049567f9a)

This img is when flag is not added
![MicrosoftTeams-image (59)](https://github.com/MicrosoftDocs/CommunityToolkit/assets/63170841/a3c6ba85-4b89-4650-89df-85f3d475004f)

### Page URL

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/extensions/keyboard-extensions

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/extensions/keyboard-extensions.md

### Document Version Independent Id

57c31da0-038c-eccc-c2f5-2a63ced6e571

### Article author

@PureWeen

### Metadata

* ID: 57c31da0-038c-eccc-c2f5-2a63ced6e571 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by bijington** [comment]
I don't know if this is an issue but to seek further assistance you should raise this on the code repository rather than the docs repository. Are you able to do that please? https://github.com/CommunityToolkit/Maui
