### ISSUE TITLE
Presenting a Popup - insufficient documentation

### ISSUE THREAD

**Issue by rettigcd** [MicrosoftDocs/CommunityToolkit#375]
### Type of issue

Typo

### Description

There are appears to be additional requirements for Presenting a popup that are not explained.  I had several points of confusion that took me 4+ hours to work out that could have been avoided with a little more detail in the documentation.

Point 1 - Whose view model is it?
The example shows a view model called _MyViewModel_.  Is that supposed to be (a) the host pages view model, (b) the popup's view model, or (c) some random component's view model?  I still have no idea.  I expect once I am an experienced MAUI programmer, I will know where I would want that, but as a newbie, I have no clue.

Point 2 - Why is IPopService so great? / How does the Popup get it's Binding Context set?
I don't understand why IPopupService is so great.  What problem is it solving?   From the example presented, it looked like it was automatically creating the popup's view model, attaching it to the popup and showing the popup.  So I tried it as shown and 
 I kept getting an error that the view model was null.  (The message was very confusing for the 1st 3 hours of debugging.)   Finally, I got it to work by adding the popup's view model to its constructor and setting it in the popup's constructor.

```
public MyPopup(MyPopupModel model) {
	InitializeComponent();
	this.BindingContext = model;
}
```
Is this how I am supposed to initialize the Binding Context?  (I have no clue.)  If it is, please add this to the documentation.

So some documentation explaining how IPopupService assigns the model to the popup would be great.

thank you.

### Page URL

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/popup

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/views/Popup.md

### Document Version Independent Id

c6126a74-78aa-2c4f-ce92-2cda527ca9fd

### Article author

@bijington

### Metadata

* ID: c6126a74-78aa-2c4f-ce92-2cda527ca9fd 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by bijington** [comment]
@rettigcd sorry to hear that the documentation doesn't make things clear. Let me answer your queries and point you to the sections of the documentation that I believe cover this. Then we can discuss how to make this clearer if that helps?

## Point 1 - Whose view model is it?

It is the view model that belongs to the popup.

We have this section:

> The IPopupService makes it possible to register a popup view and **its associated view model.** The ability to show a Popup can now be driven by only providing the view model making it possible to keep a clean separation between view and view model.

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/popup#ipopupservice

## Point 2 - Why is IPopService so great?

The same section explains this:

> The IPopupService makes it possible to register a popup view and its associated view model. **The ability to show a Popup can now be driven by only providing the view model making it possible to keep a clean separation between view and view model.**

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/popup#ipopupservice

## Point 2 - How does the Popup get it's Binding Context set?

It doesn't. This is where I think we are lacking in documentation. We can add in an explicit section to state that this is still a requirement of the develop to do this. And the approach is exactly as you have described.

Out of interest what error message did you receive when you tried your approach?

**Comment by jfversluis** [comment]
No response for a long time so assuming this issue has been resolved, thank you!
