### ISSUE TITLE
recognitionResult doesn't detect end of phrase and return

### ISSUE THREAD

**Issue by sej69** [MicrosoftDocs/CommunityToolkit#380]
The sample on this page:  [https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/essentials/speech-to-text?tabs=android](url)

 seems to show a recognitionResult return, but this never seems to happen.  I created a test project using this code and set a breakpoint on "if (recognitionResult.IsSuccessful)" and it never hits.

I thought it may have something to do with the interface I had set up per the documentation:

`    public interface ISpeechToText
    {
        Task<bool> RequestPermissions();

        Task<string> Listen(CultureInfo culture,
            IProgress<string> recognitionResult,
            CancellationToken cancellationToken);
    }`

// speech recognition code using the Interface:

`       private ISpeechToText speechToText;
                 public SpeechListener(IAudioManager am, Iris.ISpeechToText stt)
        {
            speechToText = stt;
        }
        .....
                var recognitionResult = await _speechToText.Listen(CultureInfo.GetCultureInfo("en-us"),
                new Progress<string>(partialText =>
                {

                    Debug.WriteLine("--- " + partialText + "---");

                    //RecognitionText += partialText + " "; // demo code shows to use +/, but that duplicates incoming text.
                    RecognitionText = partialText + " ";  // this doesn't duplicate the incoming text, but it does continue to report an additional time after the timer end.

                }), cancellationToken);`

But even when I switch it up to using SpeechtoText.Default.ListenAsync()... eg:

            _cancellationToken = cancellationToken;

            var recognitionResult = await SpeechToText.Default.ListenAsync(CultureInfo.GetCultureInfo("en-us"),
                new Progress<string>(partialText =>
                {
                    Debug.WriteLine("--- " + partialText + "---");
                    RecognitionText += PartialText; // need to do += here or it won't add the additional words
                    }), cancellationToken);
            if (recognitionResult.IsSuccessful) // breakpoint here
            {
                RecognitionText = recognitionResult.Text;
            }
            else
            {
                await Toast.Make(recognitionResult.Exception?.Message ?? "Unable to recognize speech").Show(CancellationToken.None);
            }

This doesn't end the recognitionResult either.  This method stays open and continues to recognize text.

To make matters worse, running the SpeechToText.Default... vs the iSpeechToText() variant seems to work "better".  I've had to create timing routines as the ListenAsync never returns anything; it just keeps listening and spitting out info.

When running the interface version (iSpeechToText), it keeps coming back and reporting the same text one more time so it awakens my timer routing again.  I can write some code to get around this behavior, but I shouldn't have to...

I pulled the interface out, but then I ran into an issue with the SpeechToText dropping the bluetooth headset AppDelegate config:

`    public override bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
    {

        SetAudioSession();

        return base.FinishedLaunching(application, launchOptions);
    }

    public bool SetAudioSession()
    {

        var audioSession = AVAudioSession.SharedInstance();
        var err = audioSession.SetCategory(AVAudioSessionCategory.PlayAndRecord, AVAudioSessionCategoryOptions.AllowBluetooth |
                                            AVAudioSessionCategoryOptions.AllowAirPlay | AVAudioSessionCategoryOptions.DefaultToSpeaker);

        if (err != null)
            return false;

        err = audioSession.SetActive(true);

        if (err != null)
            return false;

        return true;

    }`

This works when the ISpeechRecognizer interface is used, but not the SpeechRecognizer.Default.ListenAsync.  The headphone icon on the iPad goes away until I exit the app and then it shows up again and all audio destined to the audioManager interface goes through the iPad only.  However, it seems the mic on the headphones still works through bluetooth.  I've tracked it down to the "ListenAsync" method, if I comment this out, it works.  If I add it back in, it doesn't.  If I change it back to the interface iSpeechToText, it does work with my timing routines to get spoken text, but the method never returns.

I'd love to have the ListenAsync to detect silence and report back if possible.  Or I can continue to use my timing routines, but I think something is broken with the API here.

**Comment by sej69** [comment]
This is running on an iPad 10, current / most recent hardware version.

**Comment by bijington** [comment]
Is this the same issue that you raised over here: https://github.com/CommunityToolkit/Maui/issues/1645

**Comment by sej69** [comment]
There it is; I was looking for that.  Its with additional testing/info and another set of issues.

**Comment by bijington** [comment]
Most maintainers don't monitor this repository as it's only for the docs. Are you ok to migrate this issue over to the code repository please?

**Comment by sej69** [comment]
Moved
