### ISSUE TITLE
Benutzeroberfläche statt BEnutzeroberfläche

### ISSUE THREAD

**Issue by AOgai** [MicrosoftDocs/CommunityToolkit#381]
### Type of issue

Typo

### Description

> Nachfolgend finden Sie ein Beispiel für eine **BEnutzeroberfläche**, die mit XAML erstellt wurde. Diese Beispiel-UI ist mit dem folgenden ViewModel verbunden. StateContainerViewModel

### Page URL

https://learn.microsoft.com/de-de/dotnet/communitytoolkit/maui/layouts/statecontainer

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/layouts/StateContainer.md

### Document Version Independent Id

751a5a65-3406-7e60-660b-4c9e87bf6372

### Article author

@nicjay

### Metadata

* ID: 751a5a65-3406-7e60-660b-4c9e87bf6372 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by jfversluis** [comment]
I'm sorry I'm not clear on what the issue is here. If there is still something not right according to you, please open a new issue, preferably in English, with a description of what you're seeing in the documentation and what doesn't seem right to you, thanks!
