### ISSUE TITLE
Mala documentación

### ISSUE THREAD

**Issue by Uranus-Peru** [MicrosoftDocs/CommunityToolkit#382]
### Type of issue

Typo

### Description

[Escriba sus comentarios aquí]
No inicializan, le falta la inicialización.

### Page URL

https://learn.microsoft.com/es-es/dotnet/communitytoolkit/maui/extensions/keyboard-extensions

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/extensions/keyboard-extensions.md

### Document Version Independent Id

57c31da0-038c-eccc-c2f5-2a63ced6e571

### Article author

@PureWeen

### Metadata

* ID: 57c31da0-038c-eccc-c2f5-2a63ced6e571 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by jfversluis** [comment]
I'm sorry I'm not clear on what the issue is here. If there is still something not right according to you, please open a new issue, preferably in English, with a description of what you're seeing in the documentation and what doesn't seem right to you, thanks!
