### ISSUE TITLE
You need version information to verify what version this was introduced.

### ISSUE THREAD

**Issue by nick5454** [MicrosoftDocs/CommunityToolkit#390]
### Type of issue

Typo

### Description

[Enter feedback here]
I'm trying to use the AnimationBehavior and it doesn't exist. There is not any information to verify which version this code was introduced or it's dependencies.

### Page URL

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/behaviors/animation-behavior

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/behaviors/animation-behavior.md

### Document Version Independent Id

66e0ce03-3699-d4b6-83c5-08d8b3f15bef

### Article author

@bijington

### Metadata

* ID: 66e0ce03-3699-d4b6-83c5-08d8b3f15bef 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by bijington** [comment]
We don't include version information about when features were introduced, the documentation reflects the latest version.

That being said the docs page was written in September 2022 and ties to version 1.3.0. I suspect you are using a version newer than that so it should exist.

**Comment by jfversluis** [comment]
No response for a long time so assuming this issue has been resolved, thank you!
