### ISSUE TITLE
Email Validation fails if the domain char count is more then 64 for EmailValidationBehavior 

### ISSUE THREAD

**Issue by khagesh-medtronic** [MicrosoftDocs/CommunityToolkit#400]
### Type of issue

Code doesn't work

### Description

Email validation of EmailValidationBehavior fails if we have more than 64 char in the domain part of the email address.
Here is an example : SignUpLogIn@AndroidBackButtonForgotPasswordEmailNotAssociatedwithAnAccountAndroid.in

With Xamarin this use to work. But in Maui the validation is failing for the above example email address.

### Page URL

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/behaviors/email-validation-behavior

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/behaviors/email-validation-behavior.md

### Document Version Independent Id

don't know

### Article author

don't know

**Comment by bijington** [comment]
This is by design based on this standard:

> The maximum total length of a user name or other local-part is 64
      characters.

https://www.ietf.org/rfc/rfc2821.txt
