### ISSUE TITLE
.NET MAUI

### ISSUE THREAD

**Issue by vmostr** [MicrosoftDocs/CommunityToolkit#404]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/index.md

### Document Version Independent Id

f2fb5332-4c1b-fc63-1be9-9032440ff424

### Article author

@bijington

### Metadata

* ID: f2fb5332-4c1b-fc63-1be9-9032440ff424 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by bijington** [comment]
@Vmostr what exactly is the issue?

**Comment by jfversluis** [comment]
No response for a long time so assuming this issue has been resolved, thank you!
