### ISSUE TITLE
C# Sample code does not work

### ISSUE THREAD

**Issue by BruceHaley** [MicrosoftDocs/CommunityToolkit#406]
### Type of issue

Code doesn't work

### Description

I was not able to get The C# sample code to work in my new MAUI project. I imagine the code sample is outmoded.

To start, the `using CommunityToolkit.Maui.Alerts;` statement gets the error "type or namespace name 'Alerts' does not exist".

Which NuGet packages to install is not made clear. I installed CommunityToolkit.Maui and CommunityToolkit.Maui.Core. That did not help.

Thanks.
--Bruce

### Page URL

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/alerts/toast?tabs=android

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/alerts/toast.md

### Document Version Independent Id

8536c827-5a35-ebdd-51fd-0a184bfe1d69

### Article author

@VladislavAntonyuk

### Metadata

* ID: 8536c827-5a35-ebdd-51fd-0a184bfe1d69 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by bijington** [comment]
@BruceHaley you should only need CommunityToolkit.Maui. Did your issue get resolved? The code sample is correct, perhaps Visual Studio needed to be restarted?

**Comment by jfversluis** [comment]
No response for 2 weeks so assuming this is resolved!
