### ISSUE TITLE
Please include required using directive for AVFoundation

### ISSUE THREAD

**Issue by tedcalhoon** [MicrosoftDocs/CommunityToolkit#417]
### Type of issue

Missing information

### Description

Hi, regarding...
https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/mediaelement?tabs=android#bypassing-the-ios-silent-switch
...I found that I had to add the following using directive to get the code sample to work:

#if IOS
using AVFoundation;
#endif

### Page URL

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/mediaelement?tabs=android

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/views/MediaElement.md

### Document Version Independent Id

d60d04b7-bb5f-24c6-4281-923117d3eb4a

### Article author

@jfversluis

### Metadata

* ID: d60d04b7-bb5f-24c6-4281-923117d3eb4a 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by jfversluis** [comment]
Thanks for letting us know, this should be fixed now! I opted for fully qualifying the type in the code itself rather than adding extra compiler directives elsewhere in the file.

**Comment by jfversluis** [comment]
Whoops, you are totally right 😅 updated again!
