### ISSUE TITLE
using CommunityToolkit.Maui.MediaElement; is not needed and cannot be added

### ISSUE THREAD

**Issue by sqlguy6212** [MicrosoftDocs/CommunityToolkit#421]
### Type of issue

Code doesn't work

### Description

[Enter feedback here]
using CommunityToolkit.Maui.MediaElement; is not needed and cannot be added

### Page URL

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/mediaelement?tabs=windows

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/views/MediaElement.md

### Document Version Independent Id

d60d04b7-bb5f-24c6-4281-923117d3eb4a

### Article author

@jfversluis

### Metadata

* ID: d60d04b7-bb5f-24c6-4281-923117d3eb4a 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by jfversluis** [comment]
Can you elaborate a bit more? What doesn't work? Did you add the MediaElement NuGet package? It's a separate package?

**Comment by sqlguy6212** [comment]
Added package
![image](https://github.com/MicrosoftDocs/CommunityToolkit/assets/18104594/38b457a2-4811-4d7b-b314-de4642b2111a)

Added the using statement to MauiProgram.cs
using CommunityToolkit.Maui.MediaElement;

Got the following error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'MediaElement' does not exist in the namespace 'CommunityToolkit.Maui' (are you missing an assembly reference?)	NHLMaui (net8.0-android), NHLMaui (net8.0-ios), NHLMaui (net8.0-maccatalyst), NHLMaui (net8.0-windows10.0.19041.0)	C:\NewestNHLApp\NHLMaui\NHLMaui\MauiProgram.cs	3	Active

**Comment by bijington** [comment]
Oh there is an error in our documentation! You should just need to add this using statement `using CommunityToolkit.Maui;`
