### ISSUE TITLE
Example for BoolToObjectConverter seems wrong

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/CommunityToolkit#424]
### Type of issue

Code doesn't work

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/bool-to-object-converter

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/bool-to-object-converter.md

### Document Version Independent Id

caad5065-e7f7-1e6b-9487-030fab102d8c

### Article author

@bijington

### Metadata

* ID: caad5065-e7f7-1e6b-9487-030fab102d8c 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by bijington** [comment]
Thanks for raising this, I have opened this PR: https://github.com/MicrosoftDocs/CommunityToolkit/pull/425. What do you think?
