### ISSUE TITLE
Media Element on iOS doesnt work when served redirected url

### ISSUE THREAD

**Issue by kablammyman** [MicrosoftDocs/CommunityToolkit#427]
So, I made a sample test. I placed an 2 copies of audio file on my webserver. One copy of the file is in an easily accessible location, while the other copy can only be accessed via a php script. The php "redirection" is how i add a lil bit of obscurity to my media so anyone cant just steal my content.

Heres the issue, Android and Windows have no issues accessing the media using the php script but iOS cant. However, when the media is in an easily accessible location, the iOS version of mediaElement works just fine.

I think this also applies to IAudioPlayer since I'm getting the same behavior.

I'll also add that only in iOS, when I use a media element on an mp4 (served from that php file) i haven't played before, the video will play just fine the first time. However, when I leave that page and then return to that page (its a transient) to watch the same video, I get the play button with the arrow crossed out. I do not have this problem If I try to play that video in a webview on iOS.

So, I have a test project I can show this with, but Im not sure if what Im trying is "allowed" on iOS and I need to change my approach or change the settings or if its just a bug,

**Comment by bijington** [comment]
Thank you for the detailed explanation. You will likely get more information if you raise this as a bug on the toolkit repository https://github.com/CommunityToolkit/Maui. This is just the repository for the documentation and isn't monitored as well.

**Comment by jfversluis** [comment]
Indeed not a docs issue, please raise with the appropriate repository. Thanks!

**Comment by kablammyman** [comment]
sorry about that guys, here is the new link:

https://github.com/CommunityToolkit/Maui/issues/1898

 you can close this one.
