### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by MiaJohnson** [MicrosoftDocs/CommunityToolkit#433]
### Type of issue

Other (describe below)

### Description

[Enter feedback here]
broken link: https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui.Core/Essentials/AppTheme/AppThemeObjectOfT.shared.cs

### Page URL

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/essentials/apptheme-resources?source=recommendations#examples

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/essentials/apptheme-resources.md

### Document Version Independent Id

5244c456-7472-caac-0467-2de7563597c0

### Article author

@jfversluis

### Metadata

* ID: 5244c456-7472-caac-0467-2de7563597c0 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by jfversluis** [comment]
@MiaJohnson thank you! Fixed that now!
