### ISSUE TITLE
isEnasbled

### ISSUE THREAD

**Issue by RiccaB20** [MicrosoftDocs/CommunityToolkit#441]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/expander

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/views/Expander.md

### Document Version Independent Id

bea18169-c8a7-aa98-8d67-3e830e5e8185

### Article author

@VladislavAntonyuk

### Metadata

* ID: bea18169-c8a7-aa98-8d67-3e830e5e8185 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by bijington** [comment]
What is the issue?
