### ISSUE TITLE
useless -instructions for adding snackbar to Maui Android / Windows

### ISSUE THREAD

**Issue by sammazza** [MicrosoftDocs/CommunityToolkit#449]
### Type of issue

Typo

### Description

there's no XML code in package.appxmanifest.  VS22 shows a graphical interface.  there's not direction on how to add support for snackbars as per the instructions

### Page URL

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/alerts/toast?tabs=windows%2Candroid

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/alerts/toast.md

### Document Version Independent Id

8536c827-5a35-ebdd-51fd-0a184bfe1d69

### Article author

@VladislavAntonyuk

### Metadata

* ID: 8536c827-5a35-ebdd-51fd-0a184bfe1d69 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by bijington** [comment]
If you open the file in any editor other than Visual Studio then you will see XML. It is an XML file but Visual Studio tries to be helpful and provides a UI for editing the manifest.

You can also try right clicking on your package.appxmanifest file and choosing Open With -> Source Code Editor. Or something along those lines

**Comment by sammazza** [comment]
Yes, thank you.  I realized that after sending the comment.
Thank you for the clarification.
