### ISSUE TITLE
Documentation - AndroidManifest.xml instruction need to be updated

### ISSUE THREAD

**Issue by eworker2003** [MicrosoftDocs/CommunityToolkit#455]
### Type of issue

AndroidManifest.xml instruction need to be updated because the issue fixed.

### Description
This line 
<service android:name="CommunityToolkit.Maui.Media.Services"
should be updated to:
<service android:name="communityToolkit.maui.media.services"

See details:
[BUG FIX] Fix Android APK crash on API Level 21-24 #2047 https://github.com/CommunityToolkit/Maui/pull/2047

### Page URL

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/mediaelement?tabs=android

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/views/MediaElement.md

### Document Version Independent Id

d60d04b7-bb5f-24c6-4281-923117d3eb4a

### Article author

@jfversluis

### Metadata

* ID: d60d04b7-bb5f-24c6-4281-923117d3eb4a 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by jfversluis** [comment]
Fixed, thank you!
