### ISSUE TITLE
There is no popup library by that name

### ISSUE THREAD

**Issue by leemid1951** [MicrosoftDocs/CommunityToolkit#477]
### Type of issue

Code doesn't work

### Description

There is no CommunityToolkit.Maui.Sample.Views.Popups. If there is, there is no indication where to find it. It is clearly not included in CommunityToolkit.Maui v9.1.0 or in CommunityToolkit.Maui.Core v9.1.0.

### Page URL

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/popup

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/views/Popup.md

### Document Version Independent Id

c6126a74-78aa-2c4f-ce92-2cda527ca9fd

### Article author

@bijington

### Metadata

* ID: c6126a74-78aa-2c4f-ce92-2cda527ca9fd 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by bijington** [comment]
That is the namespace of the sample application linked from this section on that page: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/popup#examples

Which will take you to here: https://github.com/CommunityToolkit/Maui/blob/main/samples/CommunityToolkit.Maui.Sample/Pages/Views/

That is a set of examples to show how to use Popup and is not provided in the NuGet package
