### ISSUE TITLE
getting an error that , community toolkit refuse to import due to file invalid

### ISSUE THREAD

**Issue by UMAR1F** [MicrosoftDocs/CommunityToolkit#478]
### Type of issue

Missing information

### Description

[Enter feedback here]  <TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
  <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
  <WindowsSdkPackageVersion>10.0.19041.41</WindowsSdkPackageVersion>

### Page URL

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/index.md

### Document Version Independent Id

f2fb5332-4c1b-fc63-1be9-9032440ff424

### Article author

@bijington

### Metadata

* ID: f2fb5332-4c1b-fc63-1be9-9032440ff424 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by bijington** [comment]
There isn't enough information to help here. If you can provide the error message that was reported then we might be able to help. I'm just going to close this for now but feel free to reopen if you can provide the detail
