### ISSUE TITLE
cameraview

### ISSUE THREAD

**Issue by carpaci** [MicrosoftDocs/CommunityToolkit#497]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/camera-view?tabs=android

### Content source URL

https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/views/camera-view.md

### Document Version Independent Id

ddd38b0d-10d0-a000-b6aa-2769c945c4fd

### Article author

@bijington

### Metadata

* ID: ddd38b0d-10d0-a000-b6aa-2769c945c4fd 
* Service: **dotnet-communitytoolkit**
* Sub-service: **dotnet-maui-community-toolkit**

**Comment by bijington** [comment]
@davidbritch  I think these reports come from some built-in functionality from the docs site? Is there a way we can request more information from reporters? At times we get very little detail like this one and we just end up closing them

**Comment by davidbritch** [comment]
@bijington It's users/bots clicking on the "Open a documentation issue" link on a page, which takes them to a form like https://github.com/MicrosoftDocs/communitytoolkit/issues/new?template=customer-feedback.yml&pageUrl=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdotnet%2Fcommunitytoolkit%2Fmaui%2Fviews%2Fcamera-view%3Ftabs%3Dandroid&pageQueryParams=%3Ftabs%3Dandroid&contentSourceUrl=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FCommunityToolkit%2Fblob%2Fmain%2Fdocs%2Fmaui%2Fviews%2Fcamera-view.md&documentVersionIndependentId=ddd38b0d-10d0-a000-b6aa-2769c945c4fd&feedback=%0A%0A%5BEnter+feedback+here%5D%0A&author=%40bijington&metadata=*+ID%3A+ddd38b0d-10d0-a000-b6aa-2769c945c4fd+%0A*+Service%3A+**dotnet-communitytoolkit**%0A*+Sub-service%3A+**dotnet-maui-community-toolkit**, where they then don't fill out any information but do submit the form. All you can do is close them.

**Comment by bijington** [comment]
Ok thanks. That makes me happier to just close them then
