### ISSUE TITLE
The ConverterParameter should be mentioned in this page.

### ISSUE THREAD

**Issue by emorell96** [MicrosoftDocs/CommunityToolkit#77]
The new MAUI community toolkit has a ConverterParameter which is the type of the enum doing the conversion. In other versions this parameter wasn't required but now it is since if you try to convert back from an int to an enum, the code will throw argument null excepetion here: https://github.com/CommunityToolkit/Maui/blob/6d3ecd66810077bb102436cf2d264219d3cd7c04/src/CommunityToolkit.Maui/Converters/EnumToIntConverter.shared.cs#L34

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e79e0ccd-3a58-690b-3d39-a4a93a16ecae
* Version Independent ID: e79e0ccd-3a58-690b-3d39-a4a93a16ecae
* Content: [EnumToIntConverter - .NET MAUI Community Toolkit - .NET Community Toolkit](https://docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/enum-to-int-converter)
* Content Source: [docs/maui/converters/enum-to-int-converter.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/enum-to-int-converter.md)
* Product: **dotnet-communitytoolkit**
* GitHub Login: @CliffAgius
* Microsoft Alias: **bramin**

**Comment by bijington** [comment]
@emorell96 Thank you for raising the issue. I'll look over the details and see if it's something we need to fix in the docs or whether the code change really was necessary. 

cc @brminnick

**Comment by emorell96** [comment]
The code change was definitely nice IMO, since now the converter actually checks that the int is defined in the given enum. It was just a surprise when that part of the code started to throw exceptions.

**Comment by bijington** [comment]
This issue is related to this one over on the code repository: https://github.com/CommunityToolkit/Maui/issues/379
