### ISSUE TITLE
Found some typos

### ISSUE THREAD

**Issue by danielbanda** [MicrosoftDocs/CommunityToolkit#85]
I found some typos while inspecting the project.

**Comment by bijington** [comment]
You'll have to give us more context please. Which project? What typos?

**Comment by danielbanda** [comment]
@bijington 
I am talking about documentation for [dotnet](https://github.com/CommunityToolkit/dotnet)
Here's a PR that fixes what I have found/fix so far: [237](https://github.com/CommunityToolkit/dotnet/pull/237/files)

I hope that helps.

Best,
Daniel

**Comment by bijington** [comment]
@danielbanda Thanks for clarifying. Typically we should raise the issue under the repository that you will be providing the PR to. I understand it can get a little confusing when fixing some level of documentation.

Thank you for submitting the PR we really appreciate that! I don't work on that toolkit but I believe @Sergio0694 will likely check on it for you.
