### ISSUE TITLE
Add cwxtool to the repo

### ISSUE THREAD

**Issue by davidbritch** [MicrosoftDocs/CommunityToolkit#9]
Add cwxtool to the repo for auto-merging main to live.

**Comment by michael-hawker** [comment]
What's the cwxtool, can't we just use a GitHub Action workflow to do this? Happy to set this up sometime.

**Comment by davidbritch** [comment]
It's a bot, used in conjunction with a AzDO pipeline, that only merges main to live provided that main builds without errors. It's used across all the docs repos in the dotnet and MicrosoftDocs GitHub orgs.

**Comment by michael-hawker** [comment]
Thanks for the info @davidbritch, we didn't have that on our old repo. So glad we're getting all the latest tech. 🙂

**Comment by davidbritch** [comment]
Done.
